/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/collections` | `/collections`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/volunteers` | `/volunteers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(volunteer)'}/collect` | `/collect`; params?: Router.UnknownInputParams; } | { pathname: `${'/(volunteer)'}/my-collections` | `/my-collections`; params?: Router.UnknownInputParams; } | { pathname: `${'/(volunteer)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/receipt/[id]` | `/receipt/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(volunteer)'}/receipt/[id]` | `/receipt/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/collections` | `/collections`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/volunteers` | `/volunteers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(volunteer)'}/collect` | `/collect`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(volunteer)'}/my-collections` | `/my-collections`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(volunteer)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/receipt/[id]` | `/receipt/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(volunteer)'}/receipt/[id]` | `/receipt/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/collections${`?${string}` | `#${string}` | ''}` | `/collections${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/volunteers${`?${string}` | `#${string}` | ''}` | `/volunteers${`?${string}` | `#${string}` | ''}` | `${'/(volunteer)'}/collect${`?${string}` | `#${string}` | ''}` | `/collect${`?${string}` | `#${string}` | ''}` | `${'/(volunteer)'}/my-collections${`?${string}` | `#${string}` | ''}` | `/my-collections${`?${string}` | `#${string}` | ''}` | `${'/(volunteer)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/collections` | `/collections`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/volunteers` | `/volunteers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(volunteer)'}/collect` | `/collect`; params?: Router.UnknownInputParams; } | { pathname: `${'/(volunteer)'}/my-collections` | `/my-collections`; params?: Router.UnknownInputParams; } | { pathname: `${'/(volunteer)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `${'/(admin)'}/receipt/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/receipt/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(volunteer)'}/receipt/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/receipt/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(admin)'}/receipt/[id]` | `/receipt/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(volunteer)'}/receipt/[id]` | `/receipt/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
